name: TCE-pe Build - Windows

on:
  workflow_dispatch:

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  TAG_NAME: "nightly"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "04a9d8e5212d01ee1dd9478eadd9caade4f8b0d4"
  VERSION: "1.4.6"
  UPLOAD_ARTIFACT: "true"
  
  # --- CONFIGURAÇÕES DO SEU SERVIDOR (HORUS) ---
  RENDEZVOUS_SERVER: "horus.tcepe.tc.br"
  RS_PUB_KEY: "NctRD1DQC8cLPTWoUaNGDsF0Flb7TLvusYOOeBSOq6g="
  RELAY_SERVER: "horus.tcepe.tc.br"
  API_SERVER: "https://horus.tcepe.tc.br"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10
    strategy:
      fail-fast: false

  build-for-windows-flutter:
    name: Compilar Windows
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Replace engine with rustdesk custom flutter engine
        run: |
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive -Path windows-x64-release.zip -DestinationPath windows-x64-release
          mv -Force windows-x64-release/* C:/hostedtoolcache/windows/flutter/stable-${{ env.FLUTTER_VERSION }}-x64/bin/cache/artifacts/engine/windows-x64-release/

      - name: Patch flutter
        shell: bash
        run: |
          cp .github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff $(dirname $(dirname $(which flutter)))
          cd $(dirname $(dirname $(which flutter)))
          [[ "3.24.5" == ${{ env.FLUTTER_VERSION }} ]] && git apply flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.SCITER_RUST_VERSION }}
          targets: x86_64-pc-windows-msvc

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: true

      - name: Corrigir sintaxe do vcpkg.json
        shell: python
        run: |
          import json, os
          if os.path.exists('vcpkg.json'):
              with open('vcpkg.json', 'r', encoding='utf-8') as f:
                  data = json.load(f)
              if 'dependencies' in data:
                  for dep in data['dependencies']:
                      if isinstance(dep, dict) and 'version' in dep:
                          dep['version>='] = dep.pop('version')
              with open('vcpkg.json', 'w', encoding='utf-8') as f:
                  json.dump(data, f, indent=2)

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          $VCPKG_ROOT/vcpkg install --triplet x64-windows-static --x-install-root="$VCPKG_ROOT/installed"
        shell: bash

      - name: Build rustdesk
        run: |
          python ./build.py --flutter --hwcodec
        shell: bash

      - name: Download RustDeskTempTopMostWindow artifacts
        uses: actions/download-artifact@v4
        with:
          name: topmostwindow-artifacts
          path: "./rustdesk"

      - name: Preparar arquivos para o Instalador
        shell: bash
        run: |
          mkdir -p ./rustdesk
          cp -r ./flutter/build/windows/x64/runner/Release/* ./rustdesk/
          mv ./rustdesk/rustdesk.exe ./rustdesk/temp.exe
          mv ./rustdesk/temp.exe ./rustdesk/RustDesk.exe
          
      - name: Build self-extracted executable (.exe)
        shell: bash
        run: |
          sed -i '/dpiAware/d' res/manifest.xml
          pushd ./libs/portable
          pip3 install -r requirements.txt
          python3 ./generate.py -f ../../rustdesk/ -o . -e ../../rustdesk/RustDesk.exe
          popd
          mkdir -p ./SignOutput
          # O cargo sempre joga o executável compilado na pasta target/release da raiz
          mv ./target/release/rustdesk-portable-packer.exe ./SignOutput/rustdesk-${{ env.VERSION }}-x86_64.exe

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build MSI (.msi)
        run: |
          pushd ./res/msi
          python preprocess.py --arp -d ../../rustdesk
          nuget restore msi.sln
          msbuild msi.sln -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10
          mv ./Package/bin/x64/Release/en-us/Package.msi ../../SignOutput/rustdesk-${{ env.VERSION }}-x86_64.msi

      - name: Disponibilizar Instaladores Windows
        uses: actions/upload-artifact@v4
        with:
          name: instaladores-windows-tcepe
          path: ./SignOutput/
